development:
  adapter: postgresql
  encoding: unicode
  database: security_development
  pool: 5
  username: ruby
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: security_test
  pool: 5
  username: ruby
  password: root
